name: Simple condition Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build job
      run: echo "Executing Build Job"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test job
      run: echo "Executing Test Job"



