name: Repository secret

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Afficher secrets et variables
      run: |
            echo "Variable : ${{ vars.MYVAR }}"
            echo "Secret : ${{ secrets.DEMO_SECRET }}"




  
